imports = {'FormulaLanguage.ExpressionWalker': {'FormulaLanguage': 1,
                                      'FormulaLanguage.ParseNode': 1,
                                      'FormulaLanguage.Parser': 1,
                                      'Library': 1,
                                      'Library.Errors': 1},
 'FormulaLanguage.FLCellReferenceParseNode': {'FormulaLanguage': 1,
                                              'FormulaLanguage.ParseNode': 1},
 'FormulaLanguage.FLColumnReferenceParseNode': {'FormulaLanguage': 1,
                                                'FormulaLanguage.FormulaUtils': 1,
                                                'FormulaLanguage.ParseNode': 1,
                                                'Utils': 1,
                                                'Utils.CellNameUtils': 1,
                                                'Utils.ImportUtils': 1,
                                                'Utils.StringUtils': 1},
 'FormulaLanguage.FLRowReferenceParseNode': {'FormulaLanguage': 1,
                                             'FormulaLanguage.ParseNode': 1},
 'FormulaLanguage.FormulaUtils': {'FormulaLanguage': 1,
                                  'FormulaLanguage.ExpressionWalker': 1,
                                  'FormulaLanguage.ParseNode': 1,
                                  'FormulaLanguage.ParseNodeConstructors': 1,
                                  'FormulaLanguage.Parser': 1,
                                  'Library': 1,
                                  'Library.Errors': 1,
                                  'Utils': 1,
                                  'Utils.CellNameUtils': 1,
                                  'Utils.StringUtils': 1},
 'FormulaLanguage.Grammar': {'FormulaLanguage': 1,
                             'FormulaLanguage.ParseNode': 1,
                             'FormulaLanguage.ParseNodeConstructors': 1,
                             'FormulaLanguage.Tokens': 1,
                             'Library': 1,
                             'Library.Errors': 1,
                             'Utils': 1,
                             'Utils.CellNameUtils': 1,
                             'Utils.StringUtils': 1},
 'FormulaLanguage.Offsetter': {'FormulaLanguage': 1,
                               'FormulaLanguage.ExpressionWalker': 1,
                               'FormulaLanguage.ParseNode': 1,
                               'Utils': 1,
                               'Utils.CellNameUtils': 1,
                               'Utils.StringUtils': 1},
 'FormulaLanguage.ParseNodeConstructors': {'FormulaLanguage': 1,
                                           'FormulaLanguage.FLCellReferenceParseNode': 1,
                                           'FormulaLanguage.FLColumnReferenceParseNode': 1,
                                           'FormulaLanguage.FLRowReferenceParseNode': 1,
                                           'FormulaLanguage.ParseNode': 1},
 'FormulaLanguage.Parser': {'FormulaLanguage': 1,
                            'FormulaLanguage.Grammar': 1,
                            'FormulaLanguage.Tokens': 1},
 'FormulaLanguage.Tokens': {'Library': 1, 'Library.Errors': 1, 're': 1},
 'FormulaLanguage.Translator': {'FormulaLanguage': 1,
                                'FormulaLanguage.FormulaUtils': 1,
                                'FormulaLanguage.ParseNode': 1,
                                'FormulaLanguage.ParseNodeConstructors': 1,
                                'FormulaLanguage.Parser': 1,
                                'Utils': 1,
                                'Utils.CellNameUtils': 1,
                                'Utils.StringUtils': 1,
                                're': 1},
 'FormulaLanguage.WorksheetRenamer': {'FormulaLanguage': 1,
                                      'FormulaLanguage.ExpressionWalker': 1,
                                      'FormulaLanguage.FormulaUtils': 1,
                                      'FormulaLanguage.ParseNode': 1,
                                      'FormulaLanguage.ParseNodeConstructors': 1},
 'Library.BloombergAPI': {'Utils': 1, 'Utils.IterUtils': 1, 're': 1, 'sys': 1},
 'Library.Button': {'Utils': 1, 'Utils.DocumentationDecorators': 1},
 'Library.Cell': {'Library': 1,
                  'Library.CellRange': 1,
                  'Library.Currency': 1,
                  'Library.Date': 1,
                  'Library.Empty': 1,
                  'Library.SpreadsheetElement': 1,
                  'Library.Traits': 1,
                  'Library.Unit': 1,
                  'Utils': 1,
                  'Utils.BoolUtils': 1,
                  'Utils.CellNameUtils': 1,
                  'Utils.DocumentationDecorators': 1,
                  'Utils.ImportUtils': 1,
                  'Utils.NumberUtils': 1,
                  'decimal': 1,
                  're': 1,
                  'types': 1},
 'Library.CellRange': {'FormulaLanguage': 1,
                       'FormulaLanguage.FormulaUtils': 1,
                       'Library': 1,
                       'Library.Cell': 1,
                       'Library.Date': 1,
                       'Library.Empty': 1,
                       'Library.Traits': 1,
                       'Library.WorksheetSliceIndexer': 1,
                       'Utils': 1,
                       'Utils.DocumentationDecorators': 1,
                       'Utils.ImportUtils': 1},
 'Library.Col': {'Library': 1,
                 'Library.RowCol': 1,
                 'Utils': 1,
                 'Utils.DocumentationDecorators': 1},
 'Library.Currency': {'Library': 1,
                      'Library.Unit': 1,
                      'Utils': 1,
                      'Utils.DocumentationDecorators': 1,
                      'Utils.NumberUtils': 1},
 'Library.Date': {'Utils': 1,
                  'Utils.DocumentationDecorators': 1,
                  'datetime': 1,
                  're': 1},
 'Library.Engine.Chunk': {'re': 1},
 'Library.Engine.CodeGen.ColumnFormulaCodeGenerator': {'FormulaLanguage': 1,
                                                       'FormulaLanguage.ExpressionWalker': 1,
                                                       'FormulaLanguage.ParseNode': 1,
                                                       'FormulaLanguage.Translator': 1,
                                                       'Utils': 1,
                                                       'Utils.CellNameUtils': 1,
                                                       'Utils.StringUtils': 1,
                                                       'textwrap': 1},
 'Library.Engine.CodeGen.Constants': {'Library': 1,
                                      'Library.Engine': 1,
                                      'Library.Engine.Chunk': 1,
                                      'Library.Engine.Licenses': 1},
 'Library.Engine.CodeGen.GenerateCellCode': {'FormulaLanguage': 1,
                                             'FormulaLanguage.FormulaUtils': 1,
                                             'FormulaLanguage.Translator': 1,
                                             'Library': 1,
                                             'Library.Engine': 1,
                                             'Library.Engine.CodeGen': 1,
                                             'Library.Engine.CodeGen.CodeGenUtils': 1,
                                             'Library.Errors': 1,
                                             'Utils': 1,
                                             'Utils.CellNameUtils': 1,
                                             'Utils.StringUtils': 1},
 'Library.Engine.CodeGen.GenerateSections': {'FormulaLanguage': 1,
                                             'FormulaLanguage.Translator': 1,
                                             'Library': 1,
                                             'Library.Traits': 1,
                                             'Utils': 1,
                                             'Utils.CellNameUtils': 1,
                                             'Utils.DropdownUtils': 1,
                                             'codecs': 1,
                                             'itertools': 1},
 'Library.Engine.DocumentModel': {'Utils': 1,
                                  'Utils.ImmutableDict': 1,
                                  'Utils.Ranges': 1},
 'Library.Engine.DocumentModelInputStream': {'Library': 1,
                                             'Library.Date': 1,
                                             'Library.Engine': 1,
                                             'Library.Engine.Chunk': 1,
                                             'Library.Engine.ConnectionDetails': 1,
                                             'Library.Engine.DatabaseQuery': 1,
                                             'Library.Engine.DatabaseSettings': 1,
                                             'Library.Engine.DocumentModel': 1,
                                             'Library.Engine.DocumentStreamConstants': 1,
                                             'Library.Engine.NamedDataSource': 1,
                                             'Library.Engine.XmlReader': 1,
                                             'Library.Traits': 1,
                                             'Library.Worksheet': 1,
                                             'Utils': 1,
                                             'Utils.CellNameUtils': 1,
                                             'Utils.Ranges': 1,
                                             'codecs': 1},
 'Library.Engine.DocumentSplitUtils': {'Library': 1,
                                       'Library.Traits': 1,
                                       'itertools': 1},
 'Library.Engine.ResultContext': {'Library': 1,
                                  'Library.Engine': 1,
                                  'Library.Engine.Traceback': 1,
                                  'Library.Errors': 1,
                                  'Utils': 1,
                                  'sys': 1},
 'Library.Engine.Traceback': {'Library': 1,
                              'Library.Errors': 1,
                              're': 1,
                              'sys': 1},
 'Library.Errors': {'Utils': 1, 'Utils.DocumentationDecorators': 1},
 'Library.ImageWorksheet': {'Library': 1, 'Library.BaseWorksheet': 1},
 'Library.Row': {'Library': 1,
                 'Library.RowCol': 1,
                 'Utils': 1,
                 'Utils.DocumentationDecorators': 1},
 'Library.RowCol': {'Library': 1,
                    'Library.SpreadsheetElement': 1,
                    'Library.Traits': 1},
 'Library.RunWorkbook': {'Library': 1,
                         'Library.Cell': 1,
                         'Library.CellRange': 1,
                         'Library.Empty': 1,
                         'Library.Engine': 1,
                         'Library.Engine.DocumentModelInputStream': 1,
                         'Library.Errors': 1,
                         'Utils': 1,
                         'Utils.CellNameUtils': 1,
                         'Utils.DocumentationDecorators': 1,
                         'Utils.PathUtils': 1,
                         'os': 1},
 'Library.SpreadsheetElement': {'Library': 1,
                                'Library.Currency': 1,
                                'Library.Traits': 1},
 'Library.ThomsonAPI': {'Utils': 1,
                        'Utils.EventHook': 1,
                        'Utils.LockDecorator': 1,
                        'os': 1,
                        'sys': 1},
 'Library.Traits': {'Library': 1,
                    'Library.Currency': 1,
                    'Library.Unit': 1,
                    'Utils': 1,
                    'Utils.DocumentationDecorators': 1,
                    'Utils.StringUtils': 1},
 'Library.UI': {'Utils': 1, 'Utils.EventHook': 1},
 'Library.UnpackedArray': {'Library': 1,
                           'Library.GridRange': 1,
                           'Utils': 1,
                           'Utils.ImportUtils': 1},
 'Library.Workbook': {'Library': 1,
                      'Library.Errors': 1,
                      'Library.ImageWorksheet': 1,
                      'Library.Worksheet': 1,
                      'Utils': 1,
                      'Utils.DocumentationDecorators': 1},
 'Library.Worksheet': {'Library': 1,
                       'Library.BaseWorksheet': 1,
                       'Library.Cell': 1,
                       'Library.CellRange': 1,
                       'Library.Col': 1,
                       'Library.Date': 1,
                       'Library.Empty': 1,
                       'Library.Errors': 1,
                       'Library.Row': 1,
                       'Library.SpreadsheetElement': 1,
                       'Library.Traits': 1,
                       'Library.UnpackedArray': 1,
                       'Library.WorksheetSliceIndexer': 1,
                       'Utils': 1,
                       'Utils.CellNameUtils': 1,
                       'Utils.DocumentationDecorators': 1,
                       'Utils.LocationDict': 1,
                       'Utils.NumberUtils': 1,
                       'itertools': 1,
                       'sys': 1,
                       'types': 1},
 'Library.WorksheetSliceIndexer': {'Library': 1,
                                   'Library.Col': 1,
                                   'Library.Row': 1,
                                   'Utils': 1,
                                   'Utils.SlicingUtils': 1},
 'Main.BloombergCache': {'Library': 1,
                         'Library.BloombergAPI': 1,
                         'Utils': 1,
                         'Utils.LockDecorator': 1},
 'Main.CheckUpdates': {'Main': 1, 'Main.DataManager': 1, 'os': 1},
 'Main.ClipboardGlobals': {'Main': 1,
                           'Main.ClipboardProxy': 1,
                           'Main.CutRegionImpl': 1},
 'Main.ClipboardRange': {'FormulaLanguage': 1,
                         'FormulaLanguage.Offsetter': 1,
                         'Library': 1,
                         'Library.Errors': 1,
                         'Library.GridRange': 1,
                         'Library.SpreadsheetElement': 1,
                         'Library.Traits': 1,
                         'Main': 1,
                         'Main.Colors': 1,
                         'Main.DataFillPolicy': 1,
                         'Main.MoveRegionRewriter': 1},
 'Main.Colors': {'Library': 1, 'Library.Errors': 1},
 'Main.Commands.AboutCommand': {'Main': 1,
                                'Main.Commands': 1,
                                'Main.Commands.Command': 1,
                                'Main.DataManager': 1},
 'Main.Commands.BackgroundColorCommand': {'Main': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.StyleCommand': 1},
 'Main.Commands.BoldCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.ToggleStyleCommand': 1},
 'Main.Commands.BordersCommand': {'Library': 1,
                                  'Library.Traits': 1,
                                  'Main': 1,
                                  'Main.Commands': 1,
                                  'Main.Commands.StyleCommand': 1},
 'Main.Commands.CheckForUpdatesCommand': {'Main': 1,
                                          'Main.CheckUpdates': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.Command': 1,
                                          'Main.DataManager': 1},
 'Main.Commands.ClearCacheCommand': {'Main': 1,
                                     'Main.Commands': 1,
                                     'Main.Commands.Command': 1},
 'Main.Commands.ClearContentsCommand': {'Main': 1,
                                        'Main.Commands': 1,
                                        'Main.Commands.GridSelectionAwareCommand': 1},
 'Main.Commands.ClearRunWorkbookCacheCommand': {'Library': 1,
                                                'Library.RunWorkbook': 1,
                                                'Main': 1,
                                                'Main.Commands': 1,
                                                'Main.Commands.Command': 1,
                                                'Utils': 1,
                                                'Utils.ImportUtils': 1},
 'Main.Commands.ClipboardFillingCommand': {'Main': 1,
                                           'Main.ClipboardGlobals': 1,
                                           'Main.Commands': 1,
                                           'Main.Commands.GridSelectionAwareCommand': 1,
                                           'Main.LocationDataAggregator': 1,
                                           'Utils': 1,
                                           'Utils.ImportUtils': 1,
                                           'cPickle': 1},
 'Main.Commands.ColorCommand': {'Main': 1,
                                'Main.Commands': 1,
                                'Main.Commands.StyleCommand': 1},
 'Main.Commands.CommentCommand': {'Main': 1,
                                  'Main.Commands': 1,
                                  'Main.Commands.GridSelectionAwareCommand': 1,
                                  'Utils': 1,
                                  'Utils.CellNameUtils': 1},
 'Main.Commands.CopyCommand': {'Library': 1,
                               'Library.ImageWorksheet': 1,
                               'Main': 1,
                               'Main.ClipboardGlobals': 1,
                               'Main.Commands': 1,
                               'Main.Commands.ClipboardFillingCommand': 1},
 'Main.Commands.CutCommand': {'Main': 1,
                              'Main.ClipboardGlobals': 1,
                              'Main.Commands': 1,
                              'Main.Commands.ClipboardFillingCommand': 1,
                              'Main.Commands.PasteCommand': 1},
 'Main.Commands.DeleteWorksheetCommand': {'Main': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.DocumentAwareCommand': 1},
 'Main.Commands.DocumentAwareCommand': {'Main': 1,
                                        'Main.Commands': 1,
                                        'Main.Commands.Command': 1},
 'Main.Commands.DropdownCommand': {'Main': 1,
                                   'Main.Commands': 1,
                                   'Main.Commands.GridSelectionAwareCommand': 1,
                                   'Utils': 1,
                                   'Utils.DoNothing': 1},
 'Main.Commands.EditDatabaseWorksheetCommand': {'Library': 1,
                                                'Library.Engine': 1,
                                                'Library.Engine.NamedDataSource': 1,
                                                'Main': 1,
                                                'Main.Commands': 1,
                                                'Main.Commands.DocumentAwareCommand': 1,
                                                'Utils': 1,
                                                'Utils.DoNothing': 1},
 'Main.Commands.EditNamesCommand': {'FormulaLanguage': 1,
                                    'FormulaLanguage.FormulaUtils': 1,
                                    'Main': 1,
                                    'Main.Commands': 1,
                                    'Main.Commands.GridSelectionAwareCommand': 1,
                                    'Utils': 1,
                                    'Utils.CellNameUtils': 1,
                                    'Utils.DoNothing': 1,
                                    'Utils.ImportUtils': 1},
 'Main.Commands.EditWorksheetFormulaCommand': {'Library': 1,
                                               'Library.GridRange': 1,
                                               'Main': 1,
                                               'Main.Colors': 1,
                                               'Main.Commands': 1,
                                               'Main.Commands.DocumentAwareCommand': 1,
                                               'Main.DataFillPolicy': 1,
                                               'Main.LocationDataAggregator': 1,
                                               'Utils': 1,
                                               'Utils.ImportUtils': 1},
 'Main.Commands.ExitCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.Command': 1,
                               'Main.QueryBrokenClipboard': 1},
 'Main.Commands.ExportAsExcelCommand': {'Main': 1,
                                        'Main.Commands': 1,
                                        'Main.Commands.SaveAsCommand': 1,
                                        'Main.ExcelWriter': 1,
                                        'Utils': 1,
                                        'Utils.ImportUtils': 1},
 'Main.Commands.ExportAsExcelWithFormulaeCommand': {'Main': 1,
                                                    'Main.Commands': 1,
                                                    'Main.Commands.SaveAsCommand': 1,
                                                    'Main.ExcelWriter': 1,
                                                    'Utils': 1,
                                                    'Utils.ImportUtils': 1},
 'Main.Commands.ExportAsPythonClassCommand': {'Main': 1,
                                              'Main.Commands': 1,
                                              'Main.Commands.SaveAsCommand': 1,
                                              'Main.ExportPython': 1,
                                              'Utils': 1,
                                              'Utils.ImportUtils': 1},
 'Main.Commands.ExportAsPythonCommand': {'Library': 1,
                                         'Library.Engine': 1,
                                         'Library.Engine.CodeGen': 1,
                                         'Library.Engine.CodeGen.GenerateSections': 1,
                                         'Library.Engine.DocumentSplitUtils': 1,
                                         'Main': 1,
                                         'Main.Commands': 1,
                                         'Main.Commands.SaveAsCommand': 1,
                                         'Utils': 1,
                                         'Utils.ImportUtils': 1,
                                         'itertools': 1},
 'Main.Commands.FormatNumberCommand': {'Library': 1,
                                       'Library.Traits': 1,
                                       'Main': 1,
                                       'Main.Commands': 1,
                                       'Main.Commands.StyleCommand': 1},
 'Main.Commands.FormatTextCommand': {'Main': 1,
                                     'Main.Commands': 1,
                                     'Main.Commands.StyleCommand': 1,
                                     'Utils': 1,
                                     'Utils.FontUtils': 1},
 'Main.Commands.FreezeCommand': {'Library': 1,
                                 'Library.SpreadsheetElement': 1,
                                 'Main': 1,
                                 'Main.Commands': 1,
                                 'Main.Commands.GridSelectionAwareCommand': 1,
                                 'Main.Transaction': 1},
 'Main.Commands.GridSelectionAwareCommand': {'Library': 1,
                                             'Library.GridRange': 1,
                                             'Main': 1,
                                             'Main.Commands': 1,
                                             'Main.Commands.DocumentAwareCommand': 1},
 'Main.Commands.HeaderCommand': {'Main': 1,
                                 'Main.Commands': 1,
                                 'Main.Commands.GridSelectionAwareCommand': 1,
                                 'Main.GridUtils': 1,
                                 'Main.Transaction': 1,
                                 'Utils': 1,
                                 'Utils.CellNameUtils': 1},
 'Main.Commands.ImportFromExcelCommand': {'Main': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.OpenCommand': 1},
 'Main.Commands.InsertDatabaseWorksheetCommand': {'Library': 1,
                                                  'Library.Engine': 1,
                                                  'Library.Engine.NamedDataSource': 1,
                                                  'Library.Worksheet': 1,
                                                  'Main': 1,
                                                  'Main.Commands': 1,
                                                  'Main.Commands.Command': 1,
                                                  'Main.Commands.InsertWorksheetCommand': 1},
 'Main.Commands.InsertWorksheetCommand': {'Library': 1,
                                          'Library.Worksheet': 1,
                                          'Main': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.DocumentAwareCommand': 1},
 'Main.Commands.ItalicCommand': {'Main': 1,
                                 'Main.Commands': 1,
                                 'Main.Commands.ToggleStyleCommand': 1},
 'Main.Commands.LicenseCommand': {'Main': 1,
                                  'Main.Commands': 1,
                                  'Main.Commands.Command': 1,
                                  'Main.Transaction': 1},
 'Main.Commands.NewDocumentCommand': {'Main': 1,
                                      'Main.Commands': 1,
                                      'Main.Commands.Command': 1},
 'Main.Commands.OpenCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.Command': 1,
                               'Main.Settings': 1},
 'Main.Commands.PasteCommand': {'Library': 1,
                                'Library.GridRange': 1,
                                'Main': 1,
                                'Main.ClipboardRange': 1,
                                'Main.Commands': 1,
                                'Main.Commands.GridSelectionAwareCommand': 1,
                                'Main.DataFillPolicy': 1,
                                'Main.DataFillTransactions': 1,
                                'Main.LocationDataAggregator': 1,
                                'Utils': 1,
                                'Utils.ImportUtils': 1,
                                'cPickle': 1},
 'Main.Commands.PasteSpecialCommand': {'Main': 1,
                                       'Main.Commands': 1,
                                       'Main.Commands.GridSelectionAwareCommand': 1,
                                       'Main.Commands.PasteCommand': 1,
                                       'Main.DataFillPolicy': 1},
 'Main.Commands.PrintCommand': {'Library': 1,
                                'Library.ImageWorksheet': 1,
                                'Main': 1,
                                'Main.Commands': 1,
                                'Main.Commands.Command': 1,
                                'Main.DocumentPrintGridAdaptor': 1},
 'Main.Commands.RecalculateCommand': {'Main': 1,
                                      'Main.Commands': 1,
                                      'Main.Commands.Command': 1},
 'Main.Commands.RedoCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.Command': 1},
 'Main.Commands.ReloadModulesCommand': {'Main': 1,
                                        'Main.Commands': 1,
                                        'Main.Commands.Command': 1,
                                        'Main.Document': 1,
                                        'Utils': 1,
                                        'Utils.ImportUtils': 1},
 'Main.Commands.RenameWorksheetCommand': {'Main': 1,
                                          'Main.Commands': 1,
                                          'Main.Commands.Command': 1,
                                          'Main.RenameWorksheetTextBoxAdaptor': 1},
 'Main.Commands.RowColCommand': {'Library': 1,
                                 'Library.Traits': 1,
                                 'Main': 1,
                                 'Main.Commands': 1,
                                 'Main.Commands.GridSelectionAwareCommand': 1,
                                 'Main.Dimension': 1,
                                 'Main.RowColRewriter': 1,
                                 'Main.SelectionNormaliser': 1,
                                 'Main.Transaction': 1,
                                 'Utils': 1,
                                 'Utils.DoNothing': 1,
                                 'Utils.ImportUtils': 1},
 'Main.Commands.SaveAsCommand': {'Main': 1,
                                 'Main.Commands': 1,
                                 'Main.Commands.Command': 1,
                                 'Main.DocumentOutputStream': 1,
                                 'Main.Settings': 1,
                                 'Utils': 1,
                                 'Utils.ImportUtils': 1,
                                 'tempfile': 1},
 'Main.Commands.SaveCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.SaveAsCommand': 1},
 'Main.Commands.ShowBoundsCommand': {'Main': 1,
                                     'Main.Commands': 1,
                                     'Main.Commands.DocumentAwareCommand': 1,
                                     'Main.Transaction': 1},
 'Main.Commands.ShowGridCommand': {'Main': 1,
                                   'Main.Commands': 1,
                                   'Main.Commands.DocumentAwareCommand': 1,
                                   'Main.Transaction': 1},
 'Main.Commands.StartCommand': {'Main': 1,
                                'Main.Commands': 1,
                                'Main.Commands.Command': 1},
 'Main.Commands.StyleCommand': {'Library': 1,
                                'Library.Traits': 1,
                                'Main': 1,
                                'Main.Commands': 1,
                                'Main.Commands.GridSelectionAwareCommand': 1},
 'Main.Commands.SuspendRecalculationsCommand': {'Main': 1,
                                                'Main.Commands': 1,
                                                'Main.Commands.Command': 1},
 'Main.Commands.ThomsonConnectionSettingsCommand': {'Library': 1,
                                                    'Library.ThomsonAPI': 1,
                                                    'Main': 1,
                                                    'Main.Commands': 1,
                                                    'Main.Commands.Command': 1},
 'Main.Commands.ToggleStyleCommand': {'Main': 1,
                                      'Main.Commands': 1,
                                      'Main.Commands.StyleCommand': 1},
 'Main.Commands.UnderlineCommand': {'Main': 1,
                                    'Main.Commands': 1,
                                    'Main.Commands.ToggleStyleCommand': 1},
 'Main.Commands.UndoCommand': {'Main': 1,
                               'Main.Commands': 1,
                               'Main.Commands.Command': 1},
 'Main.Commands.UnpackArrayCommand': {'Main': 1,
                                      'Main.Colors': 1,
                                      'Main.Commands': 1,
                                      'Main.Commands.GridSelectionAwareCommand': 1},
 'Main.Commands.WebEditableCommand': {'Main': 1,
                                      'Main.Commands': 1,
                                      'Main.Commands.ToggleStyleCommand': 1},
 'Main.CutRegionImpl': {'Main': 1, 'Utils': 1, 'Utils.EventHook': 1},
 'Main.DataFillTransactions': {'Library': 1,
                               'Library.Col': 1,
                               'Library.GridRange': 1,
                               'Library.Row': 1,
                               'Library.SpreadsheetElement': 1,
                               'Main': 1,
                               'Main.DataFillPolicy': 1,
                               'Main.MoveRegionRewriter': 1},
 'Main.Document': {'FormulaLanguage': 1,
                   'FormulaLanguage.FormulaUtils': 1,
                   'FormulaLanguage.WorksheetRenamer': 1,
                   'Library': 1,
                   'Library.Engine': 1,
                   'Library.Engine.Chunk': 1,
                   'Library.Engine.CodeGen': 1,
                   'Library.Engine.CodeGen.ColumnFormulaCodeGenerator': 1,
                   'Library.Engine.CodeGen.Constants': 1,
                   'Library.Engine.CodeGen.GenerateCellCode': 1,
                   'Library.Engine.DocumentModel': 1,
                   'Library.Engine.Licenses': 1,
                   'Library.Engine.ResultContext': 1,
                   'Library.Errors': 1,
                   'Library.SpreadsheetElement': 1,
                   'Library.Traits': 1,
                   'Library.Workbook': 1,
                   'Library.Worksheet': 1,
                   'Main': 1,
                   'Main.BloombergCache': 1,
                   'Main.Colors': 1,
                   'Main.Commands': 1,
                   'Main.Commands.CellColorModeCommand': 1,
                   'Main.DataManager': 1,
                   'Main.MulticastListener': 1,
                   'Main.OutputStream': 1,
                   'Main.SplashScreen': 1,
                   'Main.ThomsonCache': 1,
                   'Main.Transaction': 1,
                   'Main.UpdateItem': 1,
                   'Main.WorksheetViewState': 1,
                   'Utils': 1,
                   'Utils.DoNothing': 1,
                   'Utils.EventHook': 1,
                   'Utils.ImportUtils': 1,
                   'Utils.LocationUtils': 1,
                   'Utils.LockDecorator': 1,
                   'Utils.Ranges': 1},
 'Main.DocumentCodeBoxAdaptor': {'Main': 1,
                                 'Main.Colors': 1,
                                 'Main.Document': 1,
                                 'Main.ResourceLoader': 1,
                                 'Utils': 1,
                                 'Utils.Bunch': 1},
 'Main.DocumentExportGridAdaptor': {'Library': 1,
                                    'Library.Traits': 1,
                                    'Main': 1,
                                    'Main.DocumentGridAdaptor': 1,
                                    'Main.DocumentGridAdaptorUtils': 1},
 'Main.DocumentGridAdaptor': {'Library': 1,
                              'Library.Button': 1,
                              'Library.Date': 1,
                              'Library.Engine': 1,
                              'Library.Engine.Traceback': 1,
                              'Library.UI': 1,
                              'Library.Worksheet': 1,
                              'Main': 1,
                              'Main.Colors': 1,
                              'Main.DocumentGridAdaptorUtils': 1,
                              'Utils': 1,
                              'Utils.AttributeBlockingProxy': 1,
                              'Utils.CellNameUtils': 1,
                              'Utils.DropdownUtils': 1},
 'Main.DocumentGridAdaptorUtils': {'Library': 1,
                                   'Library.Date': 1,
                                   'Library.Empty': 1,
                                   'Library.Traits': 1,
                                   'Main': 1,
                                   'Main.Colors': 1,
                                   'Main.Commands': 1,
                                   'Main.Commands.CellColorModeCommand': 1,
                                   'Utils': 1,
                                   'Utils.FontUtils': 1},
 'Main.DocumentInputStream': {'Library': 1,
                              'Library.Engine': 1,
                              'Library.Engine.DocumentModelInputStream': 1,
                              'Library.Engine.Licenses': 1,
                              'Library.Engine.XmlReader': 1,
                              'Library.GridRange': 1,
                              'Main': 1,
                              'Main.DataManager': 1,
                              'Main.Document': 1,
                              'Main.WorksheetViewState': 1},
 'Main.DocumentOutputStream': {'Library': 1,
                               'Library.Date': 1,
                               'Library.Engine': 1,
                               'Library.Engine.ConnectionDetails': 1,
                               'Library.Engine.DatabaseQuery': 1,
                               'Library.Engine.DocumentStreamConstants': 1,
                               'Library.Engine.Licenses': 1,
                               'Library.Engine.NamedDataSource': 1,
                               'Library.Traits': 1,
                               'Main': 1,
                               'RepositoryID': 1,
                               'Utils': 1,
                               'Utils.DropdownUtils': 1,
                               'Utils.Ranges': 1,
                               'codecs': 1,
                               'types': 1},
 'Main.DocumentPrintGridAdaptor': {'Main': 1, 'Main.DocumentGridAdaptor': 1},
 'Main.DocumentScreenGridAdaptor': {'Library': 1,
                                    'Library.Button': 1,
                                    'Library.GridRange': 1,
                                    'Library.Worksheet': 1,
                                    'Main': 1,
                                    'Main.ClipboardGlobals': 1,
                                    'Main.Colors': 1,
                                    'Main.DocumentGridAdaptor': 1,
                                    'Main.DragFillMouseController': 1,
                                    'Main.EditableHeaderCellRenderer': 1,
                                    'Main.GridUtils': 1,
                                    'Main.ReferenceGrabber': 1,
                                    'Main.RowHeightColWidthTransactions': 1,
                                    'Main.RowHiddenColHiddenTransactions': 1},
 'Main.DocumentTabControlAdaptor': {'Library': 1,
                                    'Library.ImageWorksheet': 1,
                                    'Library.Worksheet': 1,
                                    'Main': 1,
                                    'Main.SelectableImagePanel': 1},
 'Main.DragFillMouseController': {'Library': 1,
                                  'Library.GridRange': 1,
                                  'Main': 1,
                                  'Main.Colors': 1,
                                  'Main.DragFillTransaction': 1,
                                  'Utils': 1,
                                  'Utils.Bunch': 1,
                                  'Utils.ImportUtils': 1},
 'Main.DragFillTransaction': {'FormulaLanguage': 1,
                              'FormulaLanguage.Offsetter': 1,
                              'Library': 1,
                              'Library.Date': 1,
                              'Library.Traits': 1,
                              'Main': 1,
                              'Main.ClipboardRange': 1,
                              'Main.DataFillPolicy': 1,
                              'Main.DataFillTransactions': 1,
                              'Main.LocationDataAggregator': 1,
                              'Utils': 1,
                              'Utils.BoolUtils': 1,
                              'Utils.NumberUtils': 1,
                              'itertools': 1},
 'Main.ErrorBar': {'__future__': 1, 'math': 1},
 'Main.ExcelWriter': {'FormulaLanguage': 1,
                      'FormulaLanguage.ExpressionWalker': 1,
                      'FormulaLanguage.FormulaUtils': 1,
                      'FormulaLanguage.ParseNode': 1,
                      'FormulaLanguage.Parser': 1,
                      'Library': 1,
                      'Library.Currency': 1,
                      'Library.Date': 1,
                      'Library.Empty': 1,
                      'Library.Errors': 1,
                      'Library.ImageWorksheet': 1,
                      'Library.Unit': 1,
                      'Main': 1,
                      'Main.DocumentExportGridAdaptor': 1,
                      'Utils': 1,
                      'Utils.NumberUtils': 1},
 'Main.ExportPython': {'Library': 1,
                       'Library.Engine': 1,
                       'Library.Engine.CodeGen': 1,
                       'Library.Engine.CodeGen.GenerateSections': 1,
                       'Library.Engine.DocumentSplitUtils': 1,
                       'StringIO': 1,
                       'Utils': 1,
                       'Utils.Ranges': 1,
                       'itertools': 1},
 'Main.FindPanel': {'Main': 1, 'Main.ResourceLoader': 1},
 'Main.GridUtils': {'math': 1},
 'Main.LocationDataAggregator': {'Library': 1,
                                 'Library.Empty': 1,
                                 'Library.Traits': 1,
                                 'Main': 1,
                                 'Main.ClipboardRange': 1,
                                 'Utils': 1,
                                 'Utils.DropdownUtils': 1},
 'Main.MainForm': {'Main': 1,
                   'Main.ClipboardGlobals': 1,
                   'Main.Colors': 1,
                   'Main.Commands': 1,
                   'Main.Commands.AboutCommand': 1,
                   'Main.Commands.BackgroundColorCommand': 1,
                   'Main.Commands.BoldCommand': 1,
                   'Main.Commands.BordersCommand': 1,
                   'Main.Commands.CellColorModeCommand': 1,
                   'Main.Commands.CheckForUpdatesCommand': 1,
                   'Main.Commands.ClearCacheCommand': 1,
                   'Main.Commands.ClearContentsCommand': 1,
                   'Main.Commands.ClearRunWorkbookCacheCommand': 1,
                   'Main.Commands.ColorCommand': 1,
                   'Main.Commands.Command': 1,
                   'Main.Commands.CommentCommand': 1,
                   'Main.Commands.CopyCommand': 1,
                   'Main.Commands.CutCommand': 1,
                   'Main.Commands.DeleteWorksheetCommand': 1,
                   'Main.Commands.DropdownCommand': 1,
                   'Main.Commands.EditDatabaseWorksheetCommand': 1,
                   'Main.Commands.EditNamesCommand': 1,
                   'Main.Commands.EditWorksheetFormulaCommand': 1,
                   'Main.Commands.ExitCommand': 1,
                   'Main.Commands.ExportAsExcelCommand': 1,
                   'Main.Commands.ExportAsExcelWithFormulaeCommand': 1,
                   'Main.Commands.ExportAsPythonClassCommand': 1,
                   'Main.Commands.ExportAsPythonCommand': 1,
                   'Main.Commands.FormatNumberCommand': 1,
                   'Main.Commands.FormatTextCommand': 1,
                   'Main.Commands.FreezeCommand': 1,
                   'Main.Commands.HeaderCommand': 1,
                   'Main.Commands.ImportFromExcelCommand': 1,
                   'Main.Commands.InsertDatabaseWorksheetCommand': 1,
                   'Main.Commands.InsertWorksheetCommand': 1,
                   'Main.Commands.ItalicCommand': 1,
                   'Main.Commands.LicenseCommand': 1,
                   'Main.Commands.NewDocumentCommand': 1,
                   'Main.Commands.OpenCommand': 1,
                   'Main.Commands.PasteCommand': 1,
                   'Main.Commands.PasteSpecialCommand': 1,
                   'Main.Commands.PrintCommand': 1,
                   'Main.Commands.RecalculateCommand': 1,
                   'Main.Commands.RedoCommand': 1,
                   'Main.Commands.ReloadModulesCommand': 1,
                   'Main.Commands.RenameWorksheetCommand': 1,
                   'Main.Commands.RowColCommand': 1,
                   'Main.Commands.SaveAsCommand': 1,
                   'Main.Commands.SaveCommand': 1,
                   'Main.Commands.ShowBoundsCommand': 1,
                   'Main.Commands.ShowGridCommand': 1,
                   'Main.Commands.StartCommand': 1,
                   'Main.Commands.SuspendRecalculationsCommand': 1,
                   'Main.Commands.ThomsonConnectionSettingsCommand': 1,
                   'Main.Commands.UnderlineCommand': 1,
                   'Main.Commands.UndoCommand': 1,
                   'Main.Commands.UnpackArrayCommand': 1,
                   'Main.Commands.WebEditableCommand': 1,
                   'Main.DataManager': 1,
                   'Main.DocumentCodeBoxAdaptor': 1,
                   'Main.DocumentErrorBarAdaptor': 1,
                   'Main.DocumentScreenGridAdaptor': 1,
                   'Main.DocumentSplitterAdaptor': 1,
                   'Main.DocumentTabControlAdaptor': 1,
                   'Main.ErrorBar': 1,
                   'Main.FindPanel': 1,
                   'Main.FindPanelAdaptor': 1,
                   'Main.FormulaBar': 1,
                   'Main.OutputViewPanel': 1,
                   'Main.QueryBrokenClipboard': 1,
                   'Main.ResourceLoader': 1,
                   'Main.SplashScreen': 1,
                   'Utils': 1,
                   'Utils.EqualToAll': 1},
 'Main.MoveRegionRewriter': {'FormulaLanguage': 1,
                             'FormulaLanguage.ExpressionWalker': 1,
                             'FormulaLanguage.FormulaUtils': 1,
                             'FormulaLanguage.ParseNode': 1,
                             'FormulaLanguage.ParseNodeConstructors': 1,
                             'Utils': 1,
                             'Utils.CellNameUtils': 1},
 'Main.MulticastListener': {'Main': 1, 'Main.Settings': 1, 'Utils': 1},
 'Main.OutputViewPanel': {'Main': 1,
                          'Main.Colors': 1,
                          'Main.OutputStream': 1,
                          'Utils': 1},
 'Main.QueryBrokenClipboard': {'Main': 1,
                               'Main.ClipboardGlobals': 1,
                               'Main.DataManager': 1},
 'Main.ReferenceGrabber': {'Utils': 1, 'Utils.CellNameUtils': 1},
 'Main.ResourceLoader': {'Utils': 1},
 'Main.RowColRewriter': {'FormulaLanguage': 1,
                         'FormulaLanguage.ExpressionWalker': 1,
                         'FormulaLanguage.FormulaUtils': 1,
                         'FormulaLanguage.ParseNode': 1,
                         'Utils': 1,
                         'Utils.CellNameUtils': 1,
                         'Utils.StringUtils': 1},
 'Main.SplashScreen': {'Main': 1,
                       'Main.Colors': 1,
                       'Main.DataManager': 1,
                       'Utils': 1,
                       'Utils.EventHook': 1},
 'Main.ThomsonCache': {'Library': 1,
                       'Library.ThomsonAPI': 1,
                       'Utils': 1,
                       'Utils.LockDecorator': 1},
 'StringIO': {'errno': 1, 'sys': 1},
 'Utils.DropdownUtils': {'Library': 1,
                         'Library.Cell': 1,
                         'Library.Date': 1,
                         'types': 1},
 'Utils.ExcelReader': {'FormulaLanguage': 1,
                       'FormulaLanguage.ExpressionWalker': 1,
                       'FormulaLanguage.FormulaUtils': 1,
                       'FormulaLanguage.ParseNode': 1,
                       'FormulaLanguage.ParseNodeConstructors': 1,
                       'Library': 1,
                       'Library.Currency': 1,
                       'Library.SpreadsheetElement': 1,
                       'Library.Traits': 1,
                       'Library.Unit': 1,
                       'Library.Worksheet': 1,
                       'Utils': 1,
                       'Utils.CellNameUtils': 1,
                       'Utils.StringUtils': 1},
 'Utils.NumberUtils': {'re': 1},
 'Utils.PathUtils': {'os': 1},
 '__main__': {'Library': 1,
              'Library.Engine': 1,
              'Library.Engine.XmlReader': 1,
              'Main': 1,
              'Main.ClipboardGlobals': 1,
              'Main.DataManager': 1,
              'Main.Document': 1,
              'Main.DocumentInputStream': 1,
              'Main.MainForm': 1,
              'Main.MulticastListener': 1,
              'Main.QuerySave': 1,
              'Main.SplashScreen': 1,
              'Utils': 1,
              'Utils.EventHook': 1,
              'Utils.ExcelReader': 1,
              'Utils.ImportUtils': 1,
              'Utils.Logger': 1,
              'traceback': 1},
 '_threading_local': {'threading': 1},
 'bdb': {'__main__': 1,
         'linecache': 1,
         'os': 1,
         'repr': 1,
         'sys': 1,
         'types': 1},
 'bisect': {'_bisect': 1},
 'cmd': {'readline': 1, 'string': 1, 'sys': 1},
 'codecs': {'__builtin__': 1, '_codecs': 1, 'encodings': 1, 'sys': 1},
 'copy_reg': {'types': 1},
 'decimal': {'doctest': 1, 're': 1, 'sys': 1, 'threading': 1},
 'difflib': {'difflib': 1, 'doctest': 1, 'heapq': 1, 're': 1},
 'dis': {'opcode': 1, 'sys': 1, 'types': 1},
 'doctest': {'StringIO': 1,
             '__future__': 1,
             'difflib': 1,
             'inspect': 1,
             'linecache': 1,
             'new': 1,
             'os': 1,
             'pdb': 1,
             're': 1,
             'sys': 1,
             'tempfile': 1,
             'traceback': 1,
             'warnings': 1},
 'dummy_thread': {'traceback': 1, 'warnings': 1},
 'encodings': {'codecs': 1,
               'encodings': 1,
               'encodings.aliases': 1,
               'types': 1},
 'heapq': {'_heapq': 1, 'bisect': 1, 'itertools': 1, 'operator': 1},
 'inspect': {'dis': 1,
             'imp': 1,
             'linecache': 1,
             'operator': 1,
             'os': 1,
             're': 1,
             'string': 1,
             'sys': 1,
             'tokenize': 1,
             'types': 1},
 'linecache': {'os': 1, 'sys': 1},
 'macpath': {'os': 1, 'stat': 1},
 'new': {'types': 1},
 'ntpath': {'os': 1, 'stat': 1, 'string': 1, 'sys': 1},
 'os': {'UserDict': 1,
        'copy_reg': 1,
        'errno': 1,
        'macpath': 1,
        'ntpath': 1,
        'os': 1,
        'os2emxpath': 1,
        'popen2': 1,
        'posix': 1,
        'posixpath': 1,
        'sys': 1},
 'os2emxpath': {'os': 1, 'stat': 1, 'string': 1},
 'pdb': {'bdb': 1,
         'cmd': 1,
         'linecache': 1,
         'os': 1,
         'pprint': 1,
         're': 1,
         'readline': 1,
         'repr': 1,
         'sys': 1,
         'traceback': 1},
 'popen2': {'os': 1, 'sys': 1},
 'posixpath': {'os': 1, 'pwd': 1, 're': 1, 'stat': 1},
 'pprint': {'cStringIO': 1, 'sys': 1, 'time': 1},
 'random': {'_random': 1,
            'binascii': 1,
            'math': 1,
            'os': 1,
            'time': 1,
            'types': 1,
            'warnings': 1},
 're': {'copy_reg': 1,
        'sre_compile': 1,
        'sre_constants': 1,
        'sre_parse': 1,
        'sys': 1},
 'repr': {'__builtin__': 1, 'itertools': 1},
 'sre_compile': {'_sre': 1,
                 'array': 1,
                 'sre_constants': 1,
                 'sre_parse': 1,
                 'sys': 1},
 'sre_parse': {'sre_constants': 1, 'sys': 1},
 'string': {'re': 1, 'strop': 1},
 'tempfile': {'dummy_thread': 1,
              'errno': 1,
              'fcntl': 1,
              'os': 1,
              'random': 1,
              'thread': 1},
 'textwrap': {'re': 1, 'string': 1},
 'threading': {'_threading_local': 1,
               'collections': 1,
               'random': 1,
               'sys': 1,
               'thread': 1,
               'time': 1,
               'traceback': 1},
 'token': {'re': 1, 'sys': 1},
 'tokenize': {'re': 1, 'string': 1, 'sys': 1, 'token': 1},
 'traceback': {'linecache': 1, 'sys': 1, 'types': 1},
 'types': {'_types': 1, 'sys': 1},
 'warnings': {'linecache': 1, 're': 1, 'sys': 1, 'types': 1}}
